name: preview-env-deploy
on:
  pull_request:

jobs:
  deploy-preview:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    name: deploy-preview-env
    steps:
      - uses: actions/checkout@v2

      - name: Import secrets from Vault
        id: secrets
        uses: hashicorp/vault-action@d1720f055e0635fd932a1d2a48f87a666a57906c
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/products/camunda-docs/ci/preview-environment PREVIEW_ENV_BUCKET_NAME;
            secret/data/products/camunda-docs/ci/preview-environment PREVIEW_ENV_GCLOUD_SA_KEY;

      - name: Install Dependencies
        run: npm ci

      - name: start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: "${{ github.token }}"
          env: ${{ github.event.repository.name }}

      - name: Do something dummy
        run: sleep 20s

      - uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: "${{ github.token }}"
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        env:
          BUCKET_NAME: ${{ steps.secrets.outputs.PREVIEW_ENV_BUCKET_NAME }}
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Preview environment has successfully been deployed. You can access it on https://${{ env.BUCKET_NAME }}/pr-${{ github.event.number }}/index.html.
          edit-mode: replace
