name: Check versions

on: pull_request

jobs:
  list-pr-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout last two commits of the PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Identify files changed in next but not current, or vice versa
        run: |
          next_files=($( git diff --name-only HEAD^ | grep ^docs/ | sed 's/^docs\///')) 
          current_files=($( git diff --name-only HEAD^ | grep ^versioned_docs/version-8.3/ | sed 's/^versioned_docs\/version-8.3\///' )) 

          echo $next_files
          echo "-------------"
          echo $current_files
          echo "-------------"

          missing_files=(`echo ${next_files[@]} ${current_files[@]} | tr ' ' '\n' | sort | uniq -u`)

          echo $missing_files

          only_in_next=(`echo ${next_files[@]} ${missing_files[@]} | tr ' ' '\n' | sort | uniq -D | uniq`)
          only_in_current=(`echo ${current_files[@]} ${missing_files[@]} | tr ' ' '\n' | sort | uniq -D | uniq`)

          message=""

          if [ ${#only_in_next[@]} -gt 0 ]; then
            message+='These files were changed only in the *next* version. You might want to duplicate these changes in the *current* version.\n'
            for file in "${only_in_next[@]}"; do
              message+="  - docs/$file\n"
            done
            message+="\n"
          fi

          if [ ${#only_in_current[@]} -gt 0 ]; then
            message+='These files were changed only in the *current* version. You might want to duplicate these changes in the *next* version.\n'
            for file in "${only_in_current[@]}"; do
              message+="  - versioned_docs/version-8.3/$file\n"
            done
            message+="\n"
          fi

          echo POTENTIAL_MISSING_VERSIONS_MESSAGE="$message" >> $GITHUB_ENV
      - name: Emit message if it exists
        run: |
          echo $POTENTIAL_MISSING_VERSIONS_MESSAGE
