name: Compare to target

on: pull_request_target

jobs:
  list-pr-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Fetch target base
        run: git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Compare branch to target
        run: git diff --name-only HEAD..FETCH_HEAD | jq -R -s -c 'split("\n")[:-1]')
