name: Compare to target

on: pull_request_target

jobs:
  compare-to-target:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Fetch target base
        run: git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Compare branch to target
        run: |
          git rev-parse FETCH_HEAD
          git rev-parse HEAD
          git diff --name-only HEAD..FETCH_HEAD | jq -R -s -c 'split("\n")[:-1]'
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :wave: :robot: Just saying hi.
