name: preview-env-deploy
on:
  pull_request:

jobs:
  deploy-preview:
    runs-on: ubuntu-22.04
    timeout-minutes: 40
    name: deploy-preview-env
    steps:
      - uses: actions/checkout@v2

      - name: start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ github.token }}
          env: release

      - name: Set up Cloud SDK
        run: sleep 30s

      - name: update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ github.token }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        env:
          BUCKET_NAME: ${{ steps.secrets.outputs.PREVIEW_ENV_BUCKET_NAME }}
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Preview environment has successfully been deployed. You can access it on https://${{ env.BUCKET_NAME }}/pr-${{ github.event.number }}.
          edit-mode: replace
