name: preview-env-deploy
on:
  pull_request:
    types: [ labeled,synchronize ]

jobs:
  deploy-preview:
    if: github.event.pull_request.state != 'closed' && (contains( github.event.label.name, 'deploy') || contains( github.event.pull_request.labels.*.name, 'deploy'))
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    name: deploy-preview-env-${{ matrix.product_context }}
    env:
      BRANCH_NAME: ${{ github.head_ref }}
      PR_NUMBER: ${{ github.event.number }}
      URL: "https://preview.docs.camunda.cloud"
    steps:
      - uses: actions/checkout@v2
      - name: Import secrets
        id: secrets
        uses: hashicorp/vault-action@d1720f055e0635fd932a1d2a48f87a666a57906c
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/products/camunda-docs/ci/preview-environment PREVIEW_ENV_BUCKET_NAME;
            secret/data/products/camunda-docs/ci/preview-environment PREVIEW_ENV_GCLOUD_SA_KEY;
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
      - name: ls
        run: ls -a
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: env.PR_NUMBER
          body: |
            Preview environment has successfully been deployed. You can access it [here](${{ env.URL }}/pr-${{ env.PR_NUMBER }}).
          edit-mode: replace


