name: Check versions

on: pull_request

jobs:
  list-pr-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout last two commits of the PR
        # The last *two* commits are (1) everything in this branch, and (2) the parent of this branch.
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Capture version configuration as environment variable
        run: echo "VERSION_CONFIG=$(jq -c . < .github/workflows/check-versions-config.json)" >> $GITHUB_ENV

      - name: Capture changed files as environment variable
        run: echo "CHANGED_FILES=$(git diff --name-only HEAD^ | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_ENV

      - name: Identify missing changes
        id: identify-missing-changes
        run: |
          OUTPUT=$(node .github/workflows/steve.js)
          echo "::set-output name=result::$OUTPUT"

      - name: Build messages
        id: build-messages
        run: |
          OUTPUT=$(node .github/workflows/check-versions-build-messages.js)
          echo "::set-output name=result::$OUTPUT"
        env:
          MISSING_CHANGES: ${{ steps.identify-missing-changes.outputs.result }}

      - name: Output results
        run: |
          echo "Result from complex logic: ${{ steps.build-messages.outputs.result }}"
