name: Sync Camunda REST API

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 15 * * 4" # Runs every Thursday at 3 PM UTC
  workflow_dispatch:

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Camunda docs repository
        uses: actions/checkout@v3
        with:
          repository: camunda/camunda-docs
          path: docs

      - name: Checkout Camunda repository
        uses: actions/checkout@v3
        with:
          repository: camunda/camunda
          path: rest-spec
          sparse-checkout: zeebe/gateway-protocol/src/main/proto/rest-api.yaml
          sparse-checkout-cone-mode: false

      - name: Sync documentation
        run: |
          ls -lah
          cd docs
          git checkout -b camunda-rest-api-documentation-update
          mv ../rest-spec/zeebe/gateway-protocol/src/main/proto/rest-api.yaml api/camunda/camunda-openapi.yaml
          ls -lah
          npm i
          npm run api:generate:camunda
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
            exit 0
          fi
          git status
          git commit -am "docs: updates camunda rest api documentation"
          git status
          git push --set-upstream origin camunda-rest-api-documentation-update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Update camunda REST API"
          body: "This PR updates the camunda REST API"
          branch: "camunda-rest-api-documentation-update"
          base: "main"
